name: Python Web App CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Build Docker Image
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Build Docker Image
        run: |
          docker build -t python-webapp:latest .

  # Job 2: Run Unit and Selenium Tests
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Start Flask App in Background
        run: |
          nohup python3 app/main.py > app.log 2>&1 &
          sleep 5  # Allow server to start

      - name: Run Selenium Test
        run: |
          python3 app/tests/test_app.py

  # Job 3: Push Docker Image to Docker Hub
  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub and Push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag python-webapp:latest vetri20/python-webapp:latest
          docker push vetri20/python-webapp:latest

  # Job 4: Deploy to Kubernetes
  deploy:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Apply Kubernetes Configurations
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

  # Job 5: Monitoring with Grafana & Prometheus
  monitor:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Monitoring Stack with Docker Compose
        run: |
          docker-compose up -d --build
          sleep 20

      - name: Verify App Metrics Endpoint
        run: curl http://localhost:5000/metrics || echo "Metrics endpoint not available"

      - name: Verify Prometheus Target Status
        run: curl http://localhost:9090/targets || echo "Prometheus not responding"

      - name: Check Grafana Status
        run: curl -I http://localhost:3000/login || echo "Grafana not responding"
