name: Python Web App CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Build Docker Image
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Build Docker Image
        run: |
          docker build -t python-webapp:latest .

  # Job 2: Run Unit and Selenium Tests
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Start Flask App in Background
        run: |
          nohup python3 app/main.py > app.log 2>&1 &
          sleep 5  # Allow server to start

      - name: Run Selenium Test
        run: |
          python3 app/tests/test_app.py

  # Job 3: Package and Push Docker Image to JFrog
  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Build, Tag, and Push Docker Image
        env:
          IMAGE_NAME: trialn9oork.jfrog.io/project-docker/jfrog-docker-example-image:${{ github.run_number }}
        run: |
          jf docker build -t $IMAGE_NAME .
          jf docker push $IMAGE_NAME

      - name: Publish Build Info With JFrog CLI
        env:
          JFROG_CLI_BUILD_NAME: jfrog-docker-build-example
          JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}
        run: |
          jf rt build-collect-env
          jf rt build-add-git
          jf rt build-publish

  # Job 4: Deploy to Kubernetes
  deploy:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Apply Kubernetes Configurations
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

  # Job 5: Monitoring with Grafana & Prometheus
  monitor:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Monitoring Stack with Docker Compose
        run: |
          docker-compose up -d --build
          sleep 20

      - name: Verify App Metrics Endpoint
        run: |
          curl http://localhost:5000/metrics || echo "Metrics endpoint not available"

      - name: Verify Prometheus Target Status
        run: |
          curl http://localhost:9090/targets || echo "Prometheus not responding"

      - name: Check Grafana Status
        run: |
          curl -I http://localhost:3000/login || echo "Grafana not responding"
